Replace next10 config with next-i18next
unchainedshop/unchained-website pull request #31
Opened 2020-12-23 15:25 UTC by harryadel

We're now reliant on `next-i18next` to handle routing.

2020-12-29 16:09 UTC, fliptation commented
@harryadel when I change the language, the last part of the URL stays in the old language... after a refresh the correct url is shown...

2020-12-30 16:57 UTC, harryadel commented
Thanks for the catch @fliptation, will you please recheck?

2021-01-05 08:35 UTC, fliptation commented
@pozylon I'm not sure here, can you have a quick look? thanks.

2021-01-06 14:31 UTC, pozylon requested changes
Apart of my questions this looks technically good for me, @fliptation can you please look at this from a functional perspective?

It's fine to have i18next for the moment as next10's localization support is still a little bit too primitive and doesn't support some standard cases like a routing prefix for the default locale

2021-01-06 14:31 UTC, pozylon commented on webapp/hooks/useTranslation.js
> +import { useContext } from 'react';
Isn't this useTranslation already provided by https://react.i18next.com/latest/usetranslation-hook? Or is that something else? If it's possible to use the default useTranslation of react-i18next please use that hook instead of a custom file, if not leave it like this.

2021-01-06 14:31 UTC, pozylon commented on webapp/next.config.js
> +    { source: '/about', destination: '/ueber-uns' },
These rewrites are propably not needed?

2021-01-06 14:31 UTC, pozylon approved these changes

2021-01-06 14:40 UTC, harryadel commented on webapp/next.config.js
> +    { source: '/about', destination: '/ueber-uns' },
While using `PageLink` component to set `as` property seemingly fixed the localized URL issues, it presented a new one. Because if you're to visit `https://unchained.shop/de/karriere` directly and not by navigating from within the website you'd get 404 because indeed it's not found. So, we rely on rewrites to set true routes under the hood.

2021-01-06 14:42 UTC, harryadel commented on webapp/hooks/useTranslation.js
> +import { useContext } from 'react';
I was keeping the old code of translation because it already works and when Next-i18n-next makes use of Nextjs10 features I'd update it along. 

>And, we're keeping the old way of translation handling by listening to current language because this would add unnecessary burden of migrating current setup. But this too shall be handled as soon the next version of next-i18next lands.

2021-01-07 08:47 UTC, merged